### ISSUE TITLE
Megye kódok

### ISSUE THREAD

**Issue by dobakszilard** [amaximus/fire_protection_hu#3]
Szia!

Meg tudnád adni vagy felsorolni a megye kódokat? Köszönöm!

**Comment by amaximus** [comment]
Szia!

A README szerint:
```
county_id is the serial value of the county when counties are sorted alphabetically (1: Baranya, 2: Bács-Kiskun;...; 19: Zala; 20: Budapest).
```
azaz név szerinti sorrendbe teszed a megyeneveket és a kód az, hogy az általad keresett megye a hányadik (Budapest a kivétel).

**Comment by dobakszilard** [comment]
Köszönöm szépen!
